version: 0.2

#run-as: Linux-user-name  # Replace with actual Linux user or remove if not needed

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker-hub/username
    DOCKER_REGISTRY_PASSWORD: /docker-hub/password
    DOCKER_REGISTRY_URL: /docker-hub/docker_registry_url

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python dependencies"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Logging in to Docker registry"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest" .
      - echo "Pushing Docker image"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"

  post_build:
    commands:
      - echo "Build is Successful"
